# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='flight',
        ),
        migrations.AddField(
            model_name='city',
            name='flight',
            field=models.ManyToManyField(to='application.Flight'),
        ),
    ]
