# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180718_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='flight',
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='application.City'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src', to='application.City'),
        ),
    ]
