# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_user_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('person_name', models.CharField(max_length=70, null=True)),
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='null', max_length=70)),
                ('destination', models.CharField(default='null', max_length=70)),
                ('airline_name', models.CharField(default='null', max_length=70)),
                ('airline_id', models.CharField(default='null', max_length=70)),
                ('departure_date', models.DateTimeField(null=True)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
