# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_ticketdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='email_id',
            field=models.EmailField(max_length=55, null=True),
        ),
    ]
